-- CreateTable
CREATE TABLE `help_requests` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `type` VARCHAR(50) NOT NULL DEFAULT 'help_request',
    `name` VARCHAR(200) NOT NULL,
    `phone` VARCHAR(20) NOT NULL,
    `vin` VARCHAR(50) NULL,
    `message` TEXT NULL,
    `status` VARCHAR(20) NOT NULL DEFAULT 'new',
    `vehicle_year` INTEGER UNSIGNED NULL,
    `vehicle_brand` VARCHAR(100) NULL,
    `vehicle_model` VARCHAR(100) NULL,
    `vehicle_modification` VARCHAR(100) NULL,
    `vehicle_color` VARCHAR(50) NULL,
    `vehicle_type` VARCHAR(100) NULL,
    `vehicle_category` VARCHAR(10) NULL,
    `engine_type` VARCHAR(50) NULL,
    `engine_volume` INTEGER UNSIGNED NULL,
    `engine_power_hp` INTEGER UNSIGNED NULL,
    `engine_power_kw` DECIMAL(10, 2) NULL,
    `engine_number` VARCHAR(100) NULL,
    `body_number` VARCHAR(100) NULL,
    `chassis_number` VARCHAR(100) NULL,
    `body_type` VARCHAR(50) NULL,
    `max_mass` INTEGER UNSIGNED NULL,
    `unladen_mass` INTEGER UNSIGNED NULL,
    `transmission_type` VARCHAR(50) NULL,
    `drive_type` VARCHAR(50) NULL,
    `passenger_seats` INTEGER UNSIGNED NULL,
    `eco_class` VARCHAR(20) NULL,
    `manufacturer_country` VARCHAR(100) NULL,
    `vehicle_data` TEXT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,

    INDEX `help_requests_type_idx`(`type`),
    INDEX `help_requests_status_idx`(`status`),
    INDEX `help_requests_created_at_idx`(`created_at`),
    INDEX `help_requests_vin_idx`(`vin`),
    INDEX `help_requests_vehicle_brand_idx`(`vehicle_brand`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

